/**
 * Simple character agent API
 * This is a simple API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: jedrzejniemiera@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface Abilities { 
    strength?: number;
    dexterity?: number;
    constitution?: number;
    intelligence?: number;
    wisdom?: number;
    charisma?: number;
}